# Generated by Django 5.1 on 2024-10-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_jobpost_job_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contract'), ('IN', 'Internship'), ('FL', 'Freelance')], default='FT', max_length=2),
        ),
    ]
