# Generated by Django 5.1 on 2024-10-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_jobpost_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-time', 'Part-Time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], default='Full-Time', max_length=10),
        ),
    ]
