# Generated by Django 5.0.7 on 2024-10-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_experience_student_degree_student_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, choices=[('BTech', 'Bachelor of Technology'), ('MTech', 'Master of Technology'), ('BSc', 'Bachelor of Science'), ('MSc', 'Master of Science')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=100),
        ),
    ]
