# Generated by Django 5.0.7 on 2024-10-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_application_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='main.student'),
        ),
    ]
