# Generated by Django 5.0.7 on 2024-10-21 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_studentperformance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='main.student'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='training_programs', to='main.student'),
        ),
    ]
